CREATE TABLE TIPO_MEIO (
	SQ_TIPO_MEIO BIGINT(20)  NOT NULL AUTO_INCREMENT,
	NOME         VARCHAR(50) NOT NULL,

	PRIMARY KEY (SQ_TIPO_MEIO)
);

CREATE TABLE MEIO (
	SQ_MEIO            BIGINT(20)  NOT NULL AUTO_INCREMENT,
	NOME               VARCHAR(50) NOT NULL,
	SQ_TIPO_MEIO       BIGINT(20)  NOT NULL,
	DATA_HORA_CADASTRO DATETIME    NOT NULL,

	PRIMARY KEY (SQ_MEIO),
	CONSTRAINT FK_MEIO_TIPO_MEIO FOREIGN KEY (SQ_TIPO_MEIO) REFERENCES TIPO_MEIO (SQ_TIPO_MEIO)
);

CREATE TABLE ASSUNTO_CITACAO (
	SQ_ASSUNTO_CITACAO BIGINT(20)  NOT NULL AUTO_INCREMENT,
	DESCRICAO          VARCHAR(50) NOT NULL,

	PRIMARY KEY (SQ_ASSUNTO_CITACAO)
);

CREATE TABLE AUTOR (
	SQ_AUTOR               BIGINT(20) NOT NULL AUTO_INCREMENT,
	NOME                   VARCHAR(150) NOT NULL,
	NOME_REF_BIBLIOGRAFICA VARCHAR(150) NOT NULL,
	DATA_NASCIMENTO        DATE NOT NULL,
	DATA_FALECIMENTO       DATE,

	PRIMARY KEY (SQ_AUTOR)
);

CREATE TABLE CITACAO (
	SQ_CITACAO          BIGINT(20)   NOT NULL AUTO_INCREMENT,
	NOME                VARCHAR(50)  NOT NULL,
	SQ_AUTOR            BIGINT(20)   NOT NULL,
	SQ_MEIO             BIGINT(20)   NOT NULL,
	SQ_ASSUNTO_CITACAO  BIGINT(20)   NOT NULL,
	DATA_HORA_CADASTRO  DATETIME(6)  NOT NULL,
	DATA_HORA_ALTERACAO DATETIME(6)  NOT NULL,

	PRIMARY KEY (SQ_CITACAO),
	CONSTRAINT FK_AUTOR_CITACAO FOREIGN KEY (SQ_AUTOR) REFERENCES AUTOR (SQ_AUTOR),
	CONSTRAINT FK_MEIO_CITACAO FOREIGN KEY (SQ_MEIO) REFERENCES MEIO (SQ_MEIO),
	CONSTRAINT FK_ASSUNTO_CITACAO_CITACAO FOREIGN KEY (SQ_ASSUNTO_CITACAO) REFERENCES ASSUNTO_CITACAO (SQ_ASSUNTO_CITACAO)
);





